services:
  # конфигурация по умолчанию в *этом* файле
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  # Поиск аргументов action контроллеров в делегированных контейнерах.
  # Делегированный контейнер - Symfony\Component\DependencyInjection\ContainerInterface
  custom_arguments_resolvers.argument_resolver.delegated:
    class: Prokl\CustomArgumentResolverBundle\Service\ArgumentResolvers\DelegatingContainerArgumentResolver
    arguments: [!tagged delegated.container]
    tags:
      - { name: controller.argument_value_resolver, priority: 1600 }


  # Заместитель ServiceResolver для случаев с делегированными контейнерами
  # Должен выполняться раньше, чем ServiceResolver.
  argument_resolver.delegated_service:
    class: Prokl\CustomArgumentResolverBundle\Service\ArgumentResolvers\DelegatedServiceValueResolver
    calls:
      - setDelegatedContainers: [!tagged delegated.container]
    tags:
      - {name: controller.argument_value_resolver, priority: 60}

  Prokl\CustomArgumentResolverBundle\Service\ArgumentResolvers\DelegatedServiceValueResolver: '@argument_resolver.delegated_service'