parameters:
  csrf_protection: true
  custom_arguments_resolvers:
    defaults:
      enabled: true
    params:
      # Какие конкретно листенеры запретить (ID сервиса).
      disabled_resolvers:
      # - custom_arguments_resolvers.argument_resolver.ajax_call
      # Обрабатывать только контроллеры, не зарегистрированные сервисами.
      process_only_non_service_controller: false
      # Классы контроллеров, подлежащие обработке.
      classes_controllers:
        - 'Symfony\Bundle\FrameworkBundle\Controller\AbstractController'
services:
  # конфигурация по умолчанию в *этом* файле
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  # Прямой алиас сервис-контейнера Symfony. @service_container - deprecated.
  Psr\Container\ContainerInterface: '@service_container'

  session.instance:
    class: Symfony\Component\HttpFoundation\Session\Session

  Symfony\Component\HttpFoundation\Session\SessionInterface: '@session.instance'

  # Параметры приложения.
  parameter_bag:
    class: Symfony\Component\DependencyInjection\ParameterBag\ContainerBag
    arguments: ["@service_container"]

  # Параметры приложения. Алиас.
  Symfony\Component\DependencyInjection\ParameterBag\ContainerBagInterface: '@parameter_bag'
  Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface: '@parameter_bag'

  # CsrfTokenManager
  security.csrf.token_manager:
    class: Symfony\Component\Security\Csrf\CsrfTokenManager

  Symfony\Component\Security\Csrf\CsrfTokenManager: '@security.csrf.token_manager'
  Symfony\Component\Security\Csrf\CsrfTokenManagerInterface: '@security.csrf.token_manager'

  security.csrf.token_generator:
    class: Symfony\Component\Security\Csrf\TokenGenerator\UriSafeTokenGenerator

  Symfony\Component\Security\Csrf\TokenGenerator\UriSafeTokenGenerator: '@security.csrf.token_generator'

  #############
  # Ресолверы
  #############

  controller_resolver:
    class: Symfony\Bundle\FrameworkBundle\Controller\ControllerResolver
    arguments: ['@service_container']

  Symfony\Bundle\FrameworkBundle\Controller\ControllerResolver: '@controller_resolver'

  argument_metadata_factory:
    class: Symfony\Component\HttpKernel\ControllerMetadata\ArgumentMetadataFactory

  Symfony\Component\HttpKernel\ControllerMetadata\ArgumentMetadataFactory: '@argument_metadata_factory'

  argument_resolver:
    class: Symfony\Component\HttpKernel\Controller\ArgumentResolver
    arguments:
      - '@argument_metadata_factory'
      - [
        '@argument_resolver.request',
        '@argument_resolver.request_attribute',
        '@argument_resolver.session',
        '@argument_resolver.service',
        '@argument_resolver.default',
        '@argument_resolver.variadic',
      ]

  Symfony\Component\HttpKernel\Controller\ArgumentResolver: '@argument_resolver'

  argument_resolver.request_attribute:
    class: Symfony\Component\HttpKernel\Controller\ArgumentResolver\RequestAttributeValueResolver
    tags:
      - {name: controller.argument_value_resolver, priority: 100}

  Symfony\Component\HttpKernel\Controller\ArgumentResolver\RequestAttributeValueResolver: '@argument_resolver.request_attribute'

  argument_resolver.request:
    class: Symfony\Component\HttpKernel\Controller\ArgumentResolver\RequestValueResolver
    tags:
      - {name: controller.argument_value_resolver, priority: 50}

  Symfony\Component\HttpKernel\Controller\ArgumentResolver\RequestValueResolver: '@argument_resolver.request'

  argument_resolver.session:
    class: Symfony\Component\HttpKernel\Controller\ArgumentResolver\SessionValueResolver
    tags:
      - {name: controller.argument_value_resolver, priority: 50}

  Symfony\Component\HttpKernel\Controller\ArgumentResolver\SessionValueResolver: '@argument_resolver.session'

  argument_resolver.service:
    class: Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
    arguments: ['@service_container']
    tags:
      - {name: controller.argument_value_resolver, priority: 50}

  Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver: '@argument_resolver.service'

  argument_resolver.default:
    class: Symfony\Component\HttpKernel\Controller\ArgumentResolver\DefaultValueResolver
    tags:
      - {name: controller.argument_value_resolver, priority: -150}

  Symfony\Component\HttpKernel\Controller\ArgumentResolver\DefaultValueResolver: '@argument_resolver.default'

  argument_resolver.variadic:
    class: Symfony\Component\HttpKernel\Controller\ArgumentResolver\VariadicValueResolver
    tags:
      - {name: controller.argument_value_resolver, priority: -150}

  Symfony\Component\HttpKernel\Controller\ArgumentResolver\VariadicValueResolver: '@argument_resolver.variadic'

